//! Parsers for the DDlog language server.

#![recursion_limit="512"]

#![deny(clippy::all)]
#![deny(missing_docs)]
#![deny(unsafe_code)]

// Core functionality for the DDlog language server.
pub mod core;

use tree_sitter::Language;

// The external C-based parsers generated by ddlog-lsp/tree-sitter-ddlog.
extern {
    #[allow(dead_code)]
    #[doc(hidden)]
    fn tree_sitter_ddlog_dat() -> Language;

    #[allow(dead_code)]
    #[doc(hidden)]
    fn tree_sitter_ddlog_dl() -> Language;
}
