[package]
edition = "2021"
name = "ddlog-lsp-server"
version = "0.0.0"
authors = ["hvithrafn <hvithrafn@users.noreply.github.com>"]
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
repository = "https://github.com/ddlog-lsp/ddlog-lsp"
keywords = []
description = """
A language server implementation for DDlog.
"""

[badges]
maintenance = { status = "experimental" }

[features]
default = ["runtime-tokio"]
goldenfiles = []
runtime-agnostic = ["async-lock", "lspower/runtime-agnostic"]
runtime-tokio = ["lspower/runtime-tokio", "tokio", "tokio/rt-multi-thread", "tokio-stream"]

[build-dependencies]
anyhow = "1.0"
built = { version = "0.5", features = ["git2"] }

[dependencies]
anyhow = "1.0"
async-lock = { version = "2.3", optional = true }
bytes = "1.0"
clap = "2.33"
dashmap = "4.0"
ddlog-lsp-languages = { version = "0.0", path = "../languages" }
ddlog-lsp-syntax = { version = "0.0", path = "../syntax" }
env_logger = "0.9"
futures = "0.3"
log = "0.4"
lsp = { version = "0.91", package = "lsp-types" }
lsp-text = { version = "0.2", features = ["tree-sitter"] }
lspower = { version = "1.1", default-features = false }
pin-project-lite = "0.2"
ropey = "1.2"
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.0", features = ["fs", "io-std", "sync"], optional = true }
tokio-stream = { version = "0.1", features = ["fs"], optional = true }
twoway = "0.2"

[dependencies.tree-sitter]
package = "tree-sitter-facade"
version = "0.2"

[dev-dependencies]
criterion = "0.3"
ddlog-lsp-macros = { version = "0.0", path = "../macros" }
futures = "0.3"
glob = "0.3"
indoc = "1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
goldenfile = "1.0"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-futures = "0.4"
wasm-bindgen-test = "0.3"

[package.metadata.cargo-udeps.ignore]
normal = ["env_logger"]
